# Generated by Django 3.0.10 on 2020-10-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, help_text='Indiquez votre adresse email', max_length=254, unique=True, verbose_name='adresse email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='membre du staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superutilisateur')),
                ('is_active', models.BooleanField(default=False, verbose_name='utilisateur activé')),
                ('has_been_validated', models.BooleanField(null=True, verbose_name='compte validé ?')),
                ('is_manager', models.BooleanField(default=False, verbose_name='est-un manager ?')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='est-un docteur ?')),
                ('is_patient', models.BooleanField(default=False, verbose_name='est-un patient ?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date création compte')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='date dernière mise à jour')),
                ('first_name', models.CharField(help_text='Indiquez votre prénom', max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(help_text='Indiquez votre nom', max_length=100, verbose_name='nom de famille')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='activer les notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('patient_age', models.CharField(default='', max_length=3, verbose_name='age du patient')),
                ('birth_year', models.CharField(default='', help_text='Année de naissance du patient', max_length=4, verbose_name='année de naissance')),
                ('patient_id', models.CharField(default='', max_length=5, verbose_name='identifiant du patient')),
            ],
            options={
                'ordering': ['-user__creation_date'],
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
    ]
